# Generated by Django 4.1.7 on 2023-02-28 15:41

import django.db.models.deletion
from django.db import migrations, models

import relay_app.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BotConfig",
            fields=[
                (
                    "id",
                    models.TextField(
                        choices=[
                            ("TELEGRAM_TOKEN", "Токен телеграм-бота"),
                            (
                                "ALLOWED_CLIENTS",
                                "Разрешенные id (через запятую)",
                            ),
                        ],
                        help_text="Идентификатор параметра",
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Идентификатор",
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        help_text="Значение параметра",
                        max_length=400,
                        verbose_name="Значение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройка телеграм-бота",
                "verbose_name_plural": "Настройки телеграм-бота",
                "db_table": "bot_config",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PinData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveIntegerField(
                        help_text="Для отображения в списке",
                        unique=True,
                        verbose_name="Порядковый номер",
                    ),
                ),
                (
                    "board_num",
                    models.PositiveIntegerField(
                        choices=[
                            (3, "BOARD-3"),
                            (5, "BOARD-5"),
                            (7, "BOARD-7"),
                            (8, "BOARD-8"),
                            (10, "BOARD-10"),
                            (11, "BOARD-11"),
                            (12, "BOARD-12"),
                            (13, "BOARD-13"),
                            (15, "BOARD-15"),
                            (16, "BOARD-16"),
                            (18, "BOARD-18"),
                            (19, "BOARD-19"),
                            (21, "BOARD-21"),
                            (22, "BOARD-22"),
                            (23, "BOARD-23"),
                            (24, "BOARD-24"),
                            (26, "BOARD-26"),
                            (29, "BOARD-29"),
                            (31, "BOARD-31"),
                            (32, "BOARD-32"),
                            (33, "BOARD-33"),
                            (35, "BOARD-35"),
                            (36, "BOARD-36"),
                            (37, "BOARD-37"),
                            (38, "BOARD-38"),
                            (40, "BOARD-40"),
                        ],
                        help_text="Нумерация GPIO BOARD",
                        unique=True,
                        verbose_name="Номер пина (BOARD)",
                    ),
                ),
                (
                    "command",
                    models.CharField(
                        help_text='Например "Свет на кухне"',
                        max_length=30,
                        unique=True,
                        verbose_name="Назначение переключателя",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Необязательное поле",
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "state",
                    models.BooleanField(
                        default=False,
                        help_text="Включен или выключен",
                        verbose_name="Текущее состояние",
                    ),
                ),
                (
                    "invert_state",
                    models.BooleanField(
                        default=False,
                        help_text="Инвертировать состояние пинов на уровне "
                        'GPIO (т.е. "Включенный пин" = GPIO.LOW (gnd))',
                        verbose_name="Инвертировать состояние",
                    ),
                ),
                (
                    "visible",
                    models.BooleanField(
                        default=True,
                        help_text="Отображать ли в интерфейсах?",
                        verbose_name="Активен",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройка пина",
                "verbose_name_plural": "Настройки пинов",
                "db_table": "pin_data",
                "ordering": ["order_id"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cron_time",
                    models.CharField(
                        default="* * * * *",
                        help_text="Нотация Cron",
                        max_length=100,
                        validators=[relay_app.validators.validate_cron],
                        verbose_name="Время срабатывания",
                    ),
                ),
                (
                    "describe_cron",
                    models.TextField(
                        default="Каждую минуту",
                        max_length=200,
                        verbose_name="Описание времени выполнения",
                    ),
                ),
                (
                    "action",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Выключать"),
                            (1, "Включать"),
                            (2, "Переключать"),
                        ],
                        help_text="Действие над переключателем",
                        verbose_name="Действие",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Активна ли эта задача",
                        verbose_name="Активно",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "pin_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="relay_app.pindata",
                        verbose_name="Переключатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройка задачи по таймеру",
                "verbose_name_plural": "  Настройки задач по таймеру",
                "db_table": "schedule_data",
                "ordering": ["pin_data"],
            },
        ),
    ]
