# Generated by Django 4.1.7 on 2023-02-26 14:48
from django.contrib.auth.models import User
from django.db import migrations

from relay_app.models import BotConfig


def create_superuser(apps, schema_editor):  # noqa
    superuser = User()
    superuser.is_active = True
    superuser.is_superuser = True
    superuser.is_staff = True
    superuser.username = "admin"
    superuser.email = "admin@example.com"
    superuser.set_password("password")
    superuser.save()


def create_initial_settings(apps, schema_editor):  # noqa
    for _id in (BotConfig.TELEGRAM_TOKEN_ID, BotConfig.ALLOWED_CLIENTS_ID):
        bot_config = BotConfig()
        bot_config.id = _id
        bot_config.value = ""
        bot_config.save()


class Migration(migrations.Migration):
    dependencies = [
        ("relay_app", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_superuser),
        migrations.RunPython(create_initial_settings),
    ]
